### ISSUE TITLE
FileNotFound Exception while unzipping the file in Android

### ISSUE THREAD

**Issue by Praveencena88** [mockingbot/react-native-zip-archive#311]
**Describe the bug**
Whenever i try to unzip file to a specific destination using unZip function, It throws the warning fileNotfound. when i checked for the zip file in the respective path, it's present in the file system.

![image](https://github.com/user-attachments/assets/61a92115-fc8f-4792-8466-b86f218e57ce)

React-Native : 0.63.3
react-native-zip-archive: 7.0.0

**Comment by plrthink** [comment]
Can you attach the file you're using? It's hard to tell what's going wrong without the file and the code.

**Comment by cedced19** [comment]
Same here.

**Comment by ryanshepps** [comment]
Any updates on this? Currently getting the same error (ENOENT).

`
java.io.FileNotFoundException: /storage/emulated/0/Download/350 Scottsdale Drive_ Guelph_ ON_ Canada.zip: open failed: ENOENT (No such file or directory): Error: java.io.FileNotFoundException: /storage/emulated/0/Download/350 Scottsdale Drive_ Guelph_ ON_ Canada.zip: open failed: ENOENT (No such file or directory)
`

It's only happening on some phones for me (e.g., Samsung Galaxy S24 Ultra). With other Android and iOS apps the zip completes successfully.

**Comment by cedced19** [comment]
I solved my problem by looking at the content of the zip: on the new
android it seems when you have a subfolder with images/ inside for example,
this will probably fail because you don't have the permissions to access to
the image of the user.


Mit freundlichen Grüßen / Bien cordialement / Best regards,
Cédric JUNG


Le mar. 11 mars 2025 à 17:14, Ryan Sheppard ***@***.***> a
écrit :

**Comment by ryanshepps** [comment]
It appears the issue is with `net.lingala.zip4j.zip4j`. I compiled react-native-zip-archive locally with my own logs and was able to get the following stack trace:

```
net.lingala.zip4j.exception.ZipException: java.io.FileNotFoundException: /storage/emulated/0/Download/canada.zip: open failed: ENOENT (No such file or directory)
at net.lingala.zip4j.tasks.AsyncZipTask.performTaskWithErrorHandling(AsyncZipTask.java:58)
at net.lingala.zip4j.tasks.AsyncZipTask.execute(AsyncZipTask.java:45)
at net.lingala.zip4j.ZipFile.addFiles(ZipFile.java:319)
at net.lingala.zip4j.ZipFile.addFile(ZipFile.java:276)
at com.rnziparchive.RNZipArchiveModule$4.run(RNZipArchiveModule.java:411)
at java.lang.Thread.run(Thread.java:1012)
Caused by: java.io.FileNotFoundException: /storage/emulated/0/Download/canada.zip: open failed: ENOENT (No such file or directory)
at libcore.io.IoBridge.open(IoBridge.java:574)
at java.io.RandomAccessFile.<init>(RandomAccessFile.java:289)
at net.lingala.zip4j.io.outputstream.SplitOutputStream.<init>(SplitOutputStream.java:51)
at net.lingala.zip4j.tasks.AbstractAddFileToZipTask.addFilesToZip(AbstractAddFileToZipTask.java:66)
at net.lingala.zip4j.tasks.AddFilesToZipTask.executeTask(AddFilesToZipTask.java:33)
at net.lingala.zip4j.tasks.AddFilesToZipTask.executeTask(AddFilesToZipTask.java:20)
at net.lingala.zip4j.tasks.AsyncZipTask.performTaskWithErrorHandling(AsyncZipTask.java:51)
... 5 more
```

Unfortunately I do not understand zip4j enough to continue.

**Comment by plrthink** [comment]
@ryanshepps great insights—thanks for putting in the effort on this!

I was wondering if there are any alternatives to zip4j we could explore, since it’s no longer being actively maintained.

**Comment by plrthink** [comment]
Hi there! This issue is being closed because it has been stale for more than 3 months with no recent activity.

Please try the latest release **react-native-zip-archive v8.0.1**, which fully supports **React Native's New Architecture (TurboModules)**. The minimum requirements are now React Native ≥ 0.70.0 and React ≥ 18.0.0.

Example apps are available in the repository:
- [`playground-rn`](https://github.com/mockingbot/react-native-zip-archive/tree/master/playground-rn) — bare React Native 0.83.9 app with New Architecture enabled
- [`playground-expo`](https://github.com/mockingbot/react-native-zip-archive/tree/master/playground-expo) — Expo SDK 55.0.24 app with New Architecture enabled

If you can still reproduce this on v8.0.1, feel free to open a new issue with a minimal reproduction. Thanks!
