### ISSUE TITLE
zipWithPassword produces empty zip and fails with an exception. 

### ISSUE THREAD

**Issue by Volland** [mockingbot/react-native-zip-archive#321]
**Describe the bug**
zipWithPassword produces an empty zip and fails with an exception. 
I am using default encryption 

**To Reproduce**

```
await zipWithPassword(backupDir, zipPath, await this.passwordProvider.getPassword());
```

**Expected behavior**

**Env (please complete the following information):**
 - Device: [e.g. iPhone12 simulator]
 - OS Version: [e.g. 22]
 - Package Version: [7.0.1]

**Additional context**
zipWithPassword error {
 "stack": "Error: unable to zip\n    at promiseMethodWrapper (http://192.168.1.104:8081/index.bundle//&platform=ios&dev=true&hot=false&transform.engine=hermes&transform.bytecode=true&transform.routerRoot=app:13438:45)\n    at zipWithPassword (http://192.168.1.104:8081/index.bundle//&platform=ios&dev=true&hot=false&transform.engine=hermes&transform.bytecode=true&transform.routerRoot=app:649460:192)\n    at ?anon_0_ (http://192.168.1.104:8081/index.bundle//&platform=ios&dev=true&hot=false&transform.engine=hermes&transform.bytecode=true&transform.routerRoot=app:752800:64)\n    at next (native)\n    at asyncGeneratorStep (http://192.168.1.104:8081/index.bundle//&platform=ios&dev=true&hot=false&transform.engine=hermes&transform.bytecode=true&transform.routerRoot=app:1520:19)\n    at _next (http://192.168.1.104:8081/index.bundle//&platform=ios&dev=true&hot=false&transform.engine=hermes&transform.bytecode=true&transform.routerRoot=app:1534:29)\n    at tryCallOne (address at InternalBytecode.js:1:1180)\n    at anonymous (address at InternalBytecode.js:1:1874)\n    at apply (native)\n    at anonymous (http://192.168.1.104:8081/index.bundle//&platform=ios&dev=true&hot=false&transform.engine=hermes&transform.bytecode=true&transform.routerRoot=app:52701:26)\n    at _callTimer (http://192.168.1.104:8081/index.bundle//&platform=ios&dev=true&hot=false&transform.engine=hermes&transform.bytecode=true&transform.routerRoot=app:52580:17)\n    at _callReactNativeMicrotasksPass (http://192.168.1.104:8081/index.bundle//&platform=ios&dev=true&hot=false&transform.engine=hermes&transform.bytecode=true&transform.routerRoot=app:52625:17)\n    at callReactNativeMicrotasks (http://192.168.1.104:8081/index.bundle//&platform=ios&dev=true&hot=false&transform.engine=hermes&transform.bytecode=true&transform.routerRoot=app:52831:44)\n    at __callReactNativeMicrotasks (http://192.168.1.104:8081/index.bundle//&platform=ios&dev=true&hot=false&transform.engine=hermes&transform.bytecode=true&transform.routerRoot=app:11086:48)\n    at anonymous (http://192.168.1.104:8081/index.bundle//&platform=ios&dev=true&hot=false&transform.engine=hermes&transform.bytecode=true&transform.routerRoot=app:10859:45)\n    at __guard (http://192.168.1.104:8081/index.bundle//&platform=ios&dev=true&hot=false&transform.engine=hermes&transform.bytecode=true&transform.routerRoot=app:11058:15)\n    at flushedQueue (http://192.168.1.104:8081/index.bundle//&platform=ios&dev=true&hot=false&transform.engine=hermes&transform.bytecode=true&transform.routerRoot=app:10858:21)\n    at callFunctionReturnFlushedQueue (http://192.168.1.104:8081/index.bundle//&platform=ios&dev=true&hot=false&transform.engine=hermes&transform.bytecode=true&transform.routerRoot=app:10843:33)",
 "code": "zip_error",
 "message": "unable to zip",
 "domain": "RCTErrorDomain",
 "userInfo": null,
 "nativeStackIOS": [
  "0   DevKin.debug.dylib                  0x0000000109d179e4 RCTJSErrorFromCodeMessageAndNSError + 100",
  "1   DevKin.debug.dylib                  0x0000000109cb9e98 __41-[RCTModuleMethod processMethodSignature]_block_invoke_2.73 + 164",
  "2   DevKin.debug.dylib                  0x0000000109c1d9c4 -[RNZipArchive zipFolderWithPassword:destinationPath:password:encryptionType:resolver:rejecter:] + 460",
  "3   CoreFoundation                      0x00000001804b4760 __invoking___ + 144",
  "4   CoreFoundation                      0x00000001804b1ac4 -[NSInvocation invoke] + 276",
  "5   CoreFoundation                      0x00000001804b1d5c -[NSInvocation invokeWithTarget:] + 60",
  "6   DevKin.debug.dylib                  0x0000000109cbb590 -[RCTModuleMethod invokeWithBridge:module:arguments:] + 1892",
  "7   DevKin.debug.dylib                  0x0000000109cbf8a4 _ZN8facebook5reactL11invokeInnerEP9RCTBridgeP13RCTModuleDatajRKN5folly7dynamicEiN12_GLOBAL__N_117SchedulingContextE + 1848",
  "8   DevKin.debug.dylib                  0x0000000109cbef78 _ZZN8facebook5react15RCTNativeModule6invokeEjON5folly7dynamicEiENK3$_0clEv + 136",
  "9   DevKin.debug.dylib                  0x0000000109cbeee4 ___ZN8facebook5react15RCTNativeModule6invokeEjON5folly7dynamicEi_block_invoke + 28",
  "10  libdispatch.dylib                   0x0000000180170104 _dispatch_call_block_and_release + 24",
  "11  libdispatch.dylib                   0x0000000180171978 _dispatch_client_callout + 16",
  "12  libdispatch.dylib                   0x0000000180179b10 _dispatch_lane_serial_drain + 960",
  "13  libdispatch.dylib                   0x000000018017a688 _dispatch_lane_invoke + 388",
  "14  libdispatch.dylib                   0x0000000180185a84 _dispatch_root_queue_drain_deferred_wlh + 276",
  "15  libdispatch.dylib                   0x00000001801850d0 _dispatch_workloop_worker_thread + 448",
  "16  libsystem_pthread.dylib             0x0000000100df3b74 _pthread_wqthread + 284",
  "17  libsystem_pthread.dylib             0x0000000100df2934 start_wqthread + 8"
 ],
 "__sentry_captured__": true

**Comment by Volland** [comment]
I noticed that a short password works. Is there any limitation on password size, etc ?

**Comment by plrthink** [comment]
Interesting, I dont expect this behavior, but how long the password you're trying?

**Comment by Volland** [comment]
i use ethereum signature as password it was 132 characters long 

Something like that 
0xc3aeaffccf89278c814c44c3b745a224b142a2da6ed82400c6a3a71309d9290956eb2229844cdba2d9efe5bd12bba1450025684ac3d767b725d9eb74409a7d7c1c

**Comment by plrthink** [comment]
Hi there! This issue is being closed because it has been stale for more than 3 months with no recent activity.

Please try the latest release **react-native-zip-archive v8.0.1**, which fully supports **React Native's New Architecture (TurboModules)**. The minimum requirements are now React Native ≥ 0.70.0 and React ≥ 18.0.0.

Example apps are available in the repository:
- [`playground-rn`](https://github.com/mockingbot/react-native-zip-archive/tree/master/playground-rn) — bare React Native 0.83.9 app with New Architecture enabled
- [`playground-expo`](https://github.com/mockingbot/react-native-zip-archive/tree/master/playground-expo) — Expo SDK 55.0.24 app with New Architecture enabled

If you can still reproduce this on v8.0.1, feel free to open a new issue with a minimal reproduction. Thanks!
